//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vHackApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPs()
        {
            this.Attacks = new HashSet<Attacks>();
        }
    
        public string IP { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public System.DateTime LastAttack { get; set; }
        public long Money { get; set; }
        public long SDK { get; set; }
        public long Antivirus { get; set; }
        public long Firewall { get; set; }
        public long Spam { get; set; }
        public string Name { get; set; }
        public long IPSpoofing { get; set; }
        public long Spyware { get; set; }
        public long WinChance { get; set; }
        public long RepOnSuccess { get; set; }
        public bool Anonymous { get; set; }
        public string Hostname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attacks> Attacks { get; set; }
    }
}
