//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vHackApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPs()
        {
            this.Attacks = new HashSet<Attacks>();
        }
    
        public string IP { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> LastAttack { get; set; }
        public Nullable<long> Money { get; set; }
        public Nullable<long> SDK { get; set; }
        public Nullable<long> Antivirus { get; set; }
        public Nullable<long> Firewall { get; set; }
        public Nullable<long> Spam { get; set; }
        public string Name { get; set; }
        public Nullable<long> IPSpoofing { get; set; }
        public Nullable<long> Spyware { get; set; }
        public Nullable<long> WinChance { get; set; }
        public Nullable<long> RepOnSuccess { get; set; }
        public Nullable<bool> Anonymous { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attacks> Attacks { get; set; }
    }
}
