//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vHackApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public long Id { get; set; }
        public long Major { get; set; }
        public long Minor { get; set; }
        public long Patch { get; set; }
        public string Description { get; set; }
    }
}
